version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
    environment:
      - XDG_DATA_HOME=/commandhistory/
    command: tail -f /dev/null
    volumes:
      - ${PWD}:/app/
      - api-bashhistory:/commandhistory

volumes:
  app-bashhistory:
